version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-scheduling_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@agendamento_skla-db-1:5432/${DB_NAME:-scheduling_db}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=https://vivercatolico.com.br/api/auth/google/callback
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    networks:
      default:
        aliases:
          - app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --config /etc/cloudflared/config.yml run
    environment:
      - TUNNEL_CRED_FILE=/etc/cloudflared/tunnel-credentials.json
    volumes:
      - ./cloudflared-config.yml:/etc/cloudflared/config.yml:ro
      - /home/agabo/.cloudflared/6c6ad132-6fc6-422c-8127-194c0adf16d2.json:/etc/cloudflared/tunnel-credentials.json:ro


volumes:
  postgres_data:
